//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON
    {
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public Nullable<int> Soluong { get; set; }
        public string MaKM { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
