//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public string MaDG { get; set; }
        public string MaKH { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
