//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO
    {
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public int SoLuongNhap { get; set; }
        public Nullable<int> GiaHH { get; set; }
        public string MaNCC { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
