//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Drinks_cshtml : System.Web.WebPages.WebPage {
#line hidden
public _Page_Drinks_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\23thy\AppData\Local\Temp\46F11BC63B1F5E758246ADDEFC0D9DB2098F\3\demo_lab1\demo_lab1\Views\Home\Drinks.cshtml"
  
    ViewBag.Title = "Drinks";
    Layout = "~/Views/Shared/_LayoutBS.cshtml";


#line default
#line hidden
}
}
}
